spring.application.name=gera-elevator-system

server.port=8080

# PostgreSQL configuration. Change username/password/database as per your machine.
spring.datasource.url=jdbc:postgresql://localhost:5432/gera_elevator
spring.datasource.username=postgres
spring.datasource.password=8055
spring.datasource.driver-class-name=org.postgresql.Driver

# Auto-create/update tables when the app starts.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# GERA Elevator System configuration
gera.elevator.move-seconds-per-floor=5
gera.elevator.door-open-seconds=5
gera.elevator.door-close-seconds=10


gera.elevator.total-floors=16
gera.elevator.elevator-codes=A,B,C,D
gera.elevator.max-wait-seconds=180
#move-seconds-per-floor=10
#door-open-seconds=10
#door-close-seconds=10
gera.elevator.late-insert-max-delay-seconds=90
gera.elevator.default-capacity=12
#gera.elevator.scheduler-enabled=tru

gera.elevator.scheduler-enabled=true
gera.elevator.scheduler-tick-seconds=1